spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_trading
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8086

logging:
  level:
    com.stocktrading: DEBUG
